
<form class="form-horizontal" ng-controller="loginController">
    <div class="control-group">
        <label class="control-label" for="inputEmail">Email</label>
        <div class="controls">
            <input type="text" id="inputEmail" placeholder="Email" ng-model="credentials.email">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputPassword">Password</label>
        <div class="controls">
            <input type="password" id="inputPassword" placeholder="Password" ng-model="credentials.password">
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <label class="checkbox">
                <input type="checkbox" ng-model="credentials.remember"> Remember me
            </label>
            <button type="submit" class="btn" ng-click="login()">Login</button>
        </div>
    </div>
</form>